from __future__ import annotations

import importlib.util
import shutil
import sys
from pathlib import Path

from alignerr_plugin.task_metadata import (
    DOMAINS_BY_TASK_TYPE,
    REWARD_TYPES,
    TASK_TYPES,
    expected_ground_truth_score,
    metadata_validation_issues,
)
from alignerr_plugin.utils import load_task_toml


ROOT = Path(__file__).resolve().parents[2]


def test_master_metadata_enums() -> None:
    assert TASK_TYPES == ("ml", "mujoco", "cfd", "structures")
    assert REWARD_TYPES == (
        "continuous_scoring_function",
        "multi_deterministic_rubrics",
    )
    assert "scientific_discovery_computational_science" in DOMAINS_BY_TASK_TYPE["ml"]
    assert "multimodal_vision_perception" in DOMAINS_BY_TASK_TYPE["ml"]
    assert "physical_sciences" in DOMAINS_BY_TASK_TYPE["ml"]
    assert "physical_chemistry" in DOMAINS_BY_TASK_TYPE["ml"]
    assert "robot_dynamics_system_identification" in DOMAINS_BY_TASK_TYPE["ml"]
    assert "world_models" in DOMAINS_BY_TASK_TYPE["ml"]
    assert "multimodal_sensor_fusion" in DOMAINS_BY_TASK_TYPE["ml"]
    assert "online_system_identification" in DOMAINS_BY_TASK_TYPE["ml"]
    assert "model_environment_construction" in DOMAINS_BY_TASK_TYPE["mujoco"]
    assert "contact_rich_manipulation" in DOMAINS_BY_TASK_TYPE["mujoco"]
    assert "vortex_suppression" in DOMAINS_BY_TASK_TYPE["cfd"]
    assert "rans_simulation" in DOMAINS_BY_TASK_TYPE["cfd"]
    assert "seismic_retrofit" in DOMAINS_BY_TASK_TYPE["structures"]
    assert "topology_optimization" in DOMAINS_BY_TASK_TYPE["structures"]


def test_metadata_validation_rejects_cross_type_domain() -> None:
    issues = metadata_validation_issues(
        task_type="ml",
        domain="model_environment_construction",
        reward_type="continuous_scoring_function",
        license_id="MIT",
    )

    assert any("[difficulty].domain" in issue for issue in issues)


def test_license_required_for_ml_tasks() -> None:
    issues = metadata_validation_issues(
        task_type="ml",
        domain="scientific_discovery_computational_science",
        reward_type="continuous_scoring_function",
    )
    assert any("[difficulty].license" in issue for issue in issues)


def test_license_optional_for_non_ml_tasks() -> None:
    issues = metadata_validation_issues(
        task_type="mujoco",
        domain="locomotion",
        reward_type="multi_deterministic_rubrics",
    )
    assert issues == []


def test_license_accepts_permissive_spdx_case_insensitively() -> None:
    for value in ("Apache-2.0", "apache_2.0", "MIT", "cc0-1.0"):
        issues = metadata_validation_issues(
            task_type="ml",
            domain="scientific_discovery_computational_science",
            reward_type="continuous_scoring_function",
            license_id=value,
            license_source="https://github.com/owner/dataset/blob/main/LICENSE",
        )
        assert issues == [], f"{value!r} should be accepted"


def test_license_rejects_non_permissive() -> None:
    for value in ("GPL-3.0", "CC-BY-NC-4.0", "proprietary"):
        issues = metadata_validation_issues(
            task_type="ml",
            domain="scientific_discovery_computational_science",
            reward_type="continuous_scoring_function",
            license_id=value,
        )
        assert any("[difficulty].license" in issue for issue in issues), value


def test_license_accepts_self_generated_for_edge_cases() -> None:
    for value in ("self_generated", "self-generated", "SELF_GENERATED"):
        issues = metadata_validation_issues(
            task_type="ml",
            domain="scientific_discovery_computational_science",
            reward_type="continuous_scoring_function",
            license_id=value,
            license_source="fully synthetic data generated by solution/generate.py",
        )
        assert issues == [], f"{value!r} should be accepted"


def test_license_accepts_not_applicable_as_backcompat_alias() -> None:
    for value in ("not_applicable", "not-applicable", "NOT_APPLICABLE"):
        issues = metadata_validation_issues(
            task_type="ml",
            domain="scientific_discovery_computational_science",
            reward_type="continuous_scoring_function",
            license_id=value,
            license_source="fully synthetic data generated by solution/generate.py",
        )
        assert issues == [], f"{value!r} should still be accepted (alias)"


def test_license_source_required_for_ml_real_license() -> None:
    issues = metadata_validation_issues(
        task_type="ml",
        domain="scientific_discovery_computational_science",
        reward_type="continuous_scoring_function",
        license_id="MIT",
    )
    assert any("[difficulty].license_source" in issue for issue in issues)


def test_license_source_must_be_url_for_real_license() -> None:
    issues = metadata_validation_issues(
        task_type="ml",
        domain="scientific_discovery_computational_science",
        reward_type="continuous_scoring_function",
        license_id="MIT",
        license_source="trust me, it's MIT",
    )
    assert any("[difficulty].license_source" in issue for issue in issues)


def test_license_source_required_justification_for_self_generated() -> None:
    issues = metadata_validation_issues(
        task_type="ml",
        domain="scientific_discovery_computational_science",
        reward_type="continuous_scoring_function",
        license_id="self_generated",
    )
    assert any("[difficulty].license_source" in issue for issue in issues)


def test_license_source_justification_text_ok_for_self_generated() -> None:
    issues = metadata_validation_issues(
        task_type="ml",
        domain="scientific_discovery_computational_science",
        reward_type="continuous_scoring_function",
        license_id="self_generated",
        license_source="fully synthetic / self-authored data; no external dataset",
    )
    assert issues == []


def test_license_source_optional_for_non_ml_tasks() -> None:
    issues = metadata_validation_issues(
        task_type="mujoco",
        domain="locomotion",
        reward_type="multi_deterministic_rubrics",
    )
    assert issues == []


def test_expected_ground_truth_score_by_reward_type() -> None:
    continuous = expected_ground_truth_score(
        "continuous_scoring_function",
        deterministic_epsilon=1e-9,
    )
    deterministic = expected_ground_truth_score(
        "multi_deterministic_rubrics",
        deterministic_epsilon=1e-6,
    )

    assert continuous.target == 0.5
    assert continuous.epsilon == 0.05
    assert continuous.passed(0.51)
    assert not continuous.passed(1.0)
    assert deterministic.target == 1.0
    assert deterministic.epsilon == 1e-6


def _load_compute_score(template: str):
    scorer = (
        ROOT
        / "alignerr_plugin"
        / "src"
        / "alignerr_plugin"
        / "starter_templates"
        / template
        / "scorer"
    )
    path = scorer / "compute_score.py"
    spec = importlib.util.spec_from_file_location(f"{template}_compute_score", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(scorer))
    try:
        spec.loader.exec_module(module)
    finally:
        sys.path.remove(str(scorer))
    return module.compute_score


def test_starter_templates_match_reward_type_targets(tmp_path: Path) -> None:
    templates = (
        ROOT / "alignerr_plugin" / "src" / "alignerr_plugin" / "starter_templates"
    )

    # reward_type matches the grading style. The ml starter has no task.toml;
    # load_task_toml synthesizes it with reward_type pinned to the continuous curve.
    assert (
        load_task_toml(templates / "ml").difficulty.reward_type
        == "continuous_scoring_function"
    )
    for rubric_template in ("mujoco", "cfd", "structures"):
        assert (
            load_task_toml(templates / rubric_template).difficulty.reward_type
            == "multi_deterministic_rubrics"
        )

    # Each rubric starter's reference submission hits its 1.0 target. The ml
    # starter's no-arg compute_score() is covered elsewhere.
    mujoco_ws = tmp_path / "mujoco"
    mujoco_ws.mkdir()
    (mujoco_ws / "policy.py").write_text("def act(obs):\n    return 0\n")
    assert _load_compute_score("mujoco")(mujoco_ws, None, tmp_path)["score"] == 1.0

    cfd_ws = tmp_path / "cfd"
    cfd_ws.mkdir()
    (cfd_ws / "control.json").write_text('{"example_param": 1.0}')
    assert _load_compute_score("cfd")(cfd_ws, None, tmp_path)["score"] == 1.0

    structures_ws = tmp_path / "structures"
    structures_ws.mkdir()
    (structures_ws / "design.json").write_text('{"example_param": 1.0}')
    assert (
        _load_compute_score("structures")(structures_ws, None, tmp_path)["score"] == 1.0
    )


def test_task_toml_delivery_defaults_to_taiga() -> None:
    templates = (
        ROOT / "alignerr_plugin" / "src" / "alignerr_plugin" / "starter_templates"
    )
    assert load_task_toml(templates / "ml").delivery.platform == "taiga"


def test_prometheus_starter_declares_prometheus_delivery() -> None:
    templates = (
        ROOT / "alignerr_plugin" / "src" / "alignerr_plugin" / "starter_templates"
    )
    assert load_task_toml(templates / "prometheus").delivery.platform == "prometheus"


def test_numerical_solver_prometheus_starters_keep_task_type() -> None:
    templates = (
        ROOT / "alignerr_plugin" / "src" / "alignerr_plugin" / "starter_templates"
    )

    cfd = load_task_toml(templates / "prometheus-cfd")
    structures = load_task_toml(templates / "prometheus-structures")

    assert 'eval = false' in (templates / "prometheus-cfd" / "task.toml").read_text()
    assert cfd.delivery.platform == "prometheus"
    assert cfd.delivery.eval is False
    assert cfd.agent.user == "agent"
    assert cfd.verifier.user == "root"
    assert cfd.difficulty.task_type == "cfd"
    assert (
        'eval = false'
        in (templates / "prometheus-structures" / "task.toml").read_text()
    )
    assert structures.delivery.platform == "prometheus"
    assert structures.delivery.eval is False
    assert structures.agent.user == "agent"
    assert structures.verifier.user == "root"
    assert structures.difficulty.task_type == "structures"


def test_prometheus_eval_starters_mark_eval_delivery() -> None:
    templates = (
        ROOT / "alignerr_plugin" / "src" / "alignerr_plugin" / "starter_templates"
    )

    cfd = load_task_toml(templates / "prometheus-eval-cfd")
    structures = load_task_toml(templates / "prometheus-eval-structures")

    assert 'eval = true' in (templates / "prometheus-eval-cfd" / "task.toml").read_text()
    assert cfd.delivery.platform == "prometheus"
    assert cfd.delivery.eval is True
    assert cfd.difficulty.task_type == "cfd"
    assert (
        'eval = true'
        in (templates / "prometheus-eval-structures" / "task.toml").read_text()
    )
    assert structures.delivery.platform == "prometheus"
    assert structures.delivery.eval is True
    assert structures.difficulty.task_type == "structures"


def test_task_toml_delivery_accepts_mixed_case_platform(tmp_path: Path) -> None:
    templates = (
        ROOT / "alignerr_plugin" / "src" / "alignerr_plugin" / "starter_templates"
    )
    # A native starter (the ml starter has no task.toml).
    problem_dir = tmp_path / "mixed-case-prometheus"
    shutil.copytree(templates / "mujoco", problem_dir)
    task_toml = problem_dir / "task.toml"
    task_toml.write_text(
        task_toml.read_text() + '\n[delivery]\nplatform = "Prometheus"\n'
    )

    assert load_task_toml(problem_dir).delivery.platform == "prometheus"
